---
title: "MetaboAnalyst_custom_plot"
format: html
editor: visual
---

This file is for taking the MetaboAnalyst results and making pretty plots from them.

### Read in the metaboAnalyst Results:

```{r}
library(tidyverse)
library(ggrepel)
pathway_res_CTL = read_csv("../Cyclops_ordering/metabolon/MetaboAnalyst/Cycling_in_CTL_PseudobulkAR20Genes_jointAnalysisDefaultSettings/MetaboAnalyst_result_pathway.csv", show_col_types = F)

pathway_res_AD = read_csv("../Cyclops_ordering/metabolon/MetaboAnalyst/Cycling_in_AD_PseudoBulkAR20Genes_jointAnalysisDefaultSettings/MetaboAnalyst_result_pathway.csv", show_col_types = F)

pathway_res_Diff_Rhyth = read_csv("../Cyclops_ordering/metabolon/MetaboAnalyst/DR_p05_PseudobulkAR20Genes_jointAnalysisDefaultSettings/MetaboAnalyst_result_pathway.csv", show_col_types = F)

pathway_res_Diff_Rhyth_Lose_Rhythm = read_csv("../Cyclops_ordering/metabolon/MetaboAnalyst/DR_p05_LOSEAMP_PseudobulkAR20LoseAmpGenes_jointAnalysisDefaultSettings/MetaboAnalyst_result_pathway.csv", show_col_types = F)

pathway_res_Diff_Rhyth_Gain_Rhythm = read_csv("../Cyclops_ordering/metabolon/MetaboAnalyst/DR_p05_GAINAMP_PseudobulkAR20GainAmpGenes_jointAnalysisDefaultSettings/MetaboAnalyst_result_pathway.csv")

pathway_res_diff_mesor = read_csv("../Cyclops_ordering/metabolon/MetaboAnalyst/DM_BHQ1_PseudobulkBHQ1DiffMesorGenes_jointAnalysisDefaultSettings/MetaboAnalyst_result_pathway.csv")
```

Make the Plots:

```{r}
p1 = ggplot(pathway_res_CTL, aes(x= Impact, y = `-log10(p)`, label =str_wrap(`...1`, 25)))+
  geom_point(size = 5, color = "#0091ff", alpha = 0.7)+
  ggrepel::geom_text_repel(max.overlaps = 8, box.padding = 0.35, )+
   theme_minimal()+    
  theme(
    axis.text.x = element_text(size = 14),    # Increase x-axis text size
    axis.text.y = element_text(size = 14),    # Increase y-axis text size
    axis.title.x = element_text(size = 16),   # Increase x-axis title size
    axis.title.y = element_text(size = 16),   # Increase y-axis title size
    legend.title = element_text(size = 12)    # Increase legend title size
  )+
  ylab("-Log(p val)")
ggsave("~/Desktop/Cycling_CTL_BHQ1_jointPathwayMataboanalyst.pdf", plot = p1, width = 5, height = 5, units = "in")
```

```{r}
p2 = ggplot(pathway_res_AD, aes(x= Impact, y = `-log10(p)`, label =str_wrap(`...1`, 25)))+
  geom_point(size = 5, color = "red", alpha = 0.7)+
  ggrepel::geom_text_repel(max.overlaps = 8, box.padding = 0.35)+
   theme_minimal()+    
  theme(
    axis.text.x = element_text(size = 14),    # Increase x-axis text size
    axis.text.y = element_text(size = 14),    # Increase y-axis text size
    axis.title.x = element_text(size = 16),   # Increase x-axis title size
    axis.title.y = element_text(size = 16),   # Increase y-axis title size
    legend.title = element_text(size = 12)    # Increase legend title size
  )+
  ylab("-Log(p val)")
ggsave("~/Desktop/Cycling_AD_BHQ1_jointPathwayMataboanalyst.pdf", plot = p2, width = 5, height = 5, units = "in")
```

```{r}
p3 = ggplot(pathway_res_Diff_Rhyth, aes(x= Impact, y = `-log10(p)`, label =str_wrap(`...1`, 25)))+
  geom_point(size = 5, color = "orange", alpha = 0.7)+
  ggrepel::geom_text_repel(max.overlaps = 8, box.padding = 0.35)+
   theme_minimal()+    
  theme(
    axis.text.x = element_text(size = 14),    # Increase x-axis text size
    axis.text.y = element_text(size = 14),    # Increase y-axis text size
    axis.title.x = element_text(size = 16),   # Increase x-axis title size
    axis.title.y = element_text(size = 16),   # Increase y-axis title size
    legend.title = element_text(size = 12)    # Increase legend title size
  )+
  ylab("-Log(p val)")

ggsave("~/Desktop/DR_cycling_p05_jointPathwayMataboanalyst.pdf", plot = p3, width = 5, height = 5, units = "in")
```

```{r}
p4 = ggplot(pathway_res_Diff_Rhyth_Gain_Rhythm, aes(x= Impact, y = `-log10(p)`, label =str_wrap(`...1`, 25)))+
  geom_point(size = 5, color = "green", alpha = 0.7)+
  ggrepel::geom_text_repel(max.overlaps = 5)+
   theme_minimal()+    
  theme(
    axis.text.x = element_text(size = 14),    # Increase x-axis text size
    axis.text.y = element_text(size = 14),    # Increase y-axis text size
    axis.title.x = element_text(size = 16),   # Increase x-axis title size
    axis.title.y = element_text(size = 16),   # Increase y-axis title size
    legend.title = element_text(size = 12)    # Increase legend title size
  )+
  ylab("-Log(p val)")
```

```{r}
p5 = ggplot(pathway_res_Diff_Rhyth_Lose_Rhythm, aes(x= Impact, y = `-log10(p)`, label =str_wrap(`...1`, 25)))+
  geom_point(size = 5, color = "brown", alpha = 0.7)+
  ggrepel::geom_text_repel(max.overlaps = 5)+
   theme_minimal()+    
  theme(
    axis.text.x = element_text(size = 14),    # Increase x-axis text size
    axis.text.y = element_text(size = 14),    # Increase y-axis text size
    axis.title.x = element_text(size = 16),   # Increase x-axis title size
    axis.title.y = element_text(size = 16),   # Increase y-axis title size
    legend.title = element_text(size = 12)    # Increase legend title size
  )+
  ylab("-Log(p val)")
ggsave("~/Desktop/DR_cycling_LOSEAMP_p05_jointPathwayMataboanalyst.pdf", plot = p5, width = 5, height = 5, units = "in")
```

```{r}
p6 = ggplot(pathway_res_diff_mesor, aes(x= Impact, y = `-log10(p)`, label =str_wrap(`...1`, 25)))+
  geom_point(size = 5, color = "purple", alpha = 0.7)+
  ggrepel::geom_text_repel(max.overlaps = 5)+
   theme_minimal()+    
  theme(
    axis.text.x = element_text(size = 14),    # Increase x-axis text size
    axis.text.y = element_text(size = 14),    # Increase y-axis text size
    axis.title.x = element_text(size = 16),   # Increase x-axis title size
    axis.title.y = element_text(size = 16),   # Increase y-axis title size
    legend.title = element_text(size = 12)    # Increase legend title size
  )+
  ylab("-Log(p val)")
ggsave("~/Desktop/DM_BHQ1_jointPathwayMataboanalyst.pdf", plot = p6, width = 5, height = 5, units = "in")
```
